NGCHM/WebContent/javascript/ColorMapManager.js

Fix missing darkenHexColorIfNeeded function.

Define utility function NgChm.CMM.darkenHexColorIfNeeded

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/css/NGCHM.css
NGCHM/WebContent/javascript/CompatibilityManager.js
NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/PaneControl.js
NGCHM/WebContent/javascript/PdfGenerator.js
NGCHM/WebContent/javascript/SelectionManager.js
NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
NGCHM/src/mda/ngchm/datagenerator/GalaxyMapGen.java
NGCHM/src/mda/ngchm/datagenerator/ImportConstants.java

Pivotal Tracker items in branch insilico_041120:  
#172133638 - Gene Pattern is using GalaxyMapGen jar and, thus, getting version information for Galaxy.
#172189139 - Dragging divider off embedded panel in Galaxy, GenePattern, and embedded maps leaves divider in unfinished state.
#172226396 - Change Pane headers for Summary and Detail panes to break the word "Heatmap" into "Heat Map"
#172131824 - Putting just a comma, semicolon, or period in the search box or ending entry with a semicolon causes all columns and rows to be selected.
#172249632 - Screen being redrawn each time a user types in the search box
#172254643 - Typing into the search box and clicking anywhere on the document results in the search executing

PTs:  #172133638, #172189139, #172226396, #172131824, #172249632, and

---

NGCHM/WebContent/javascript/Linkout.js

Fixes two small bugs in the viewer:
- Incorrect selection of covariates for options in the gear dialog
- Error if attempting to select a label with multiple linkout panels open

Two bug fixes

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/css/NGCHM.css
NGCHM/WebContent/javascript/CompatibilityManager.js
NGCHM/WebContent/javascript/Dendrogram.js
NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/Linkout.js
NGCHM/WebContent/javascript/MatrixManager.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/SearchManager.js
NGCHM/WebContent/javascript/SelectionManager.js
NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
NGCHM/WebContent/javascript/UserHelpManager.js

This pull request includes the following Pivotal Tracker items:
#172607015: Restructure the appearance of the search functionality in light of changes to remove detail navigation buttons.
#172606981: Enhance search to allow navigation, clearing and execution by row or column.
#172606952: Enhance search capability to include the ability to search by covariate values.
#172564442: Dendrograms do not get unselected when the user executes a search
#172607070: Break search functionality out of the DetailHeatMapDisplay javascript file into its own JS file.

PTs: #172607015, #172606981, #172606952, #172564442, and #172607070

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/css/NGCHM.css
NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/src/mda/ngchm/datagenerator/GalaxyMapGen.java

This small update contains:
PT #172803736:  Detail buttons bar being drawn without a map being open.
Also, new version number for Galaxy Map Generator

PT #172803736:  Detail buttons bar being drawn without a map being open.

---

NGCHM/WebContent/javascript/Linkout.js

Added more user help to the Gear Dialog and refactored code for
existing help. This commit allows plugin to supply help text to
display.

Add help in Gear Dialog

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/css/NGCHM.css
NGCHM/WebContent/javascript/CompatibilityManager.js
NGCHM/WebContent/javascript/Dendrogram.js
NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/Linkout.js
NGCHM/WebContent/javascript/MatrixManager.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/PaneControl.js
NGCHM/WebContent/javascript/PdfGenerator.js
NGCHM/WebContent/javascript/SearchManager.js
NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
NGCHM/WebContent/javascript/UserHelpManager.js
NGCHM/src/mda/ngchm/datagenerator/GalaxyMapGen.java
NGCHM/src/mda/ngchm/util/NGCHM_Widgetizer.java

PT Items included in this pull request
#168120557 - PDF reporting missing values in covariates that are not missing.
#170759016 - PDF Inconsistent fonts in legend titles and    titles overwriting legends.
#173060647 - Standalone not clearing list of covariates for search when next map is opened
#173160333 - Panel gear menu doesn't close if user makes different panel selection for that panel or closes that panel completely. 
#173155631 - Unable to deselect dendrogram sections with Ctrl-click.
#173176068 - Viewer search found records count overlaps red border line.
#173181928 - If portion of search string is invalid, entire search string should be treated as invalid.
#173181816 - ScatterPlot/Pathways selections not being updated when search functionality selects new items on heat map. …

2.17.7 viewer

---

NGCHM/src/mda/ngchm/util/NGCHM_AppGenerator.java

PT #173296945: Fix minimization/widgetization process to handle the writing of 64bit png files into CSS files.

Minor AppGenerator fix for CSS content base64 image fix

---

NGCHM/WebContent/javascript/Linkout.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/PaneControl.js
NGCHM/WebContent/javascript/UserHelpManager.js

This pull request addresses issues and bugs from the latest round of testing (mostly testing by @jmelott ). 
Showstopper issues addressed by this pull request:
- If gear dialog is open when page closed, gear dialog not always removed
- Selecting row axis for Scatter Plot not implemented
- Spliting pane sometimes causes reset of PathwayMapper state, w/ no warning to user
Other issues addressed by this pull request:
- Show button in gear dialog sometimes causes console errors
- Console errors if no pathway loaded and 'APPLY' clicked
- Console errors if group has < 2 members
- No option to change lasso and selection highlight color
- Character limits for label fields in gear dialog

Testing1.2 Issues

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/javascript/CompatibilityManager.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/PdfGenerator.js
NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
NGCHM/src/mda/ngchm/datagenerator/GalaxyMapGen.java

2.17.8 PT Items Fixed:
#173419205: PDF reporting missing values in data matrix when there aren't any.
#173420970: GUI Builder - Covariate labels not completely displayed on Process Covariates page.
#173512670: PDF data matrix distribution missing some counts for the lowest breakpoint threshold.
#173514738: Change viewer, galaxy, and builder versions
Version for Viewer changed to 2.17.8

2.17.8 PTs: #173419205, #173420970, and #173512670

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/css/NGCHM.css
NGCHM/WebContent/javascript/CompatibilityManager.js
NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/Linkout.js
NGCHM/WebContent/javascript/MatrixManager.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/PaneControl.js
NGCHM/WebContent/javascript/PdfGenerator.js
NGCHM/WebContent/javascript/SearchManager.js
NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
NGCHM/src/mda/ngchm/datagenerator/GalaxyMapGen.java
NGCHM/src/mda/ngchm/datagenerator/ImportData.java
NGCHM/src/mda/ngchm/datagenerator/InputClass.java

Contents of branch to be merged to Master:
#173822671 Add validation to HeatmapDataGenerator to prevent 2 covars on the same axis with the same name.
#173967727 embedded expandable maps do not allow downloads.
#173967889 Covariate search category display sort bug
#173967925 REFLECT website not displaying properly after implementing 2.18.0
#173968107 Modify matrix selections feature to display and function when items on only one axis are selected.
#174023319 Dendro selection box not in correct location in ribbon mode if map for large maps
#174023365 Search box no longer finding labels containing the period (.) character

2.18.1 viewer

---

NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/src/mda/ngchm/datagenerator/HeatmapDataGenerator.java
NGCHM/src/mda/ngchm/datagenerator/ImportConstants.java
NGCHM/src/mda/ngchm/datagenerator/ImportData.java
NGCHM/src/mda/ngchm/datagenerator/ShaidyRMapGen.java

This pull request brings the html heat map generation logic, developed in May, into the code located in the current main branch.  It includes changes from May as well as the ShaidyRMapGen changes recently added by Bradley.

The html heat map logic added to the latest 2.18.2 code branch

---

NGCHM/WebContent/javascript/custom/custom.js

Add new linkouts from bio.gene.hugo to depmap and GTEx portals.

Add new linkouts

---

NGCHM/WebContent/javascript/CompatibilityManager.js

Move version of viewer to 2.20.0

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/javascript/CompatibilityManager.js
NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/DetailHeatMapEvent.js
NGCHM/WebContent/javascript/DetailHeatMapManager.js
NGCHM/WebContent/javascript/MatrixManager.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
NGCHM/build_ngchmApp.xml
NGCHM/src/mda/ngchm/datagenerator/GalaxyMapGen.java
NGCHM/src/mda/ngchm/datagenerator/HeatmapDataGenerator.java
NGCHM/src/mda/ngchm/datagenerator/ImportData.java
NGCHM/src/mda/ngchm/datagenerator/InputClass.java
NGCHM/src/mda/ngchm/datagenerator/InputFile.java
NGCHM/src/mda/ngchm/datagenerator/PdfGenerator.java
NGCHM/src/mda/ngchm/datagenerator/RowColData.java
NGCHM/src/mda/ngchm/util/NGCHM_AppGenerator.java
NGCHM/src/mda/ngchm/util/NGCHM_AppVersioner.java
NGCHM/src/mda/ngchm/util/NGCHM_Minimizer.java
NGCHM/src/mda/ngchm/util/NGCHM_Widgetizer.java

Pivotal Tracker items in this pull request:
PT #177310703: Lines for Column top items being drawn on top of or below top item labels if pane made small.  Top label text will also overlap each other if pane made too small and items are close in map.
PT #177484841:  Resolve client caching issues when new versions of JS and CSS files are deployed.
PT #176500992: Make json parsing errors more informative.
PT #173967619: Change zoom out logic to go to full screen via ribbon mode when in standard mode, while being able to go back to standard mode and the correct location on zoom in.

PTs #177310703, #177484841, #176500992, and #173967619

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/javascript/CompatibilityManager.js
NGCHM/WebContent/javascript/custom/custom.js
NGCHM/src/mda/ngchm/datagenerator/GalaxyMapGen.java

Adds 3D scatterplot to pane menu.  Renames Scatterplot menu item to "2D Scatterplot".  Updates NG-CHM Viewer to 2.20.2.

PT: #177930719 - Add 3D Scatterplot to 2.20.2 version of NG-CHM Viewer

---

NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/DetailHeatMapEvent.js

When the user zooms out far enough, the display mode will change from
normal mode, to a ribbon mode, to full map mode.  This patch fixes display
redrawing issues that would occur on a subsequent zoom in that attempted
to restore the originally selected display mode:
- From a vertical ribbon mode: displays trash at the top of the detail pane
- From a horizontal ribbon mode: skews the display of column covariate bars

Fix issues with detail map redraws after automatic display mode changes

---

NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/UserHelpManager.js

Fixes issues with the zoom mode buttons in detail panes:
- Zoom mode buttons could become non-functional after creating a new
sibling pane that forces the pane div to upgrade to a container div.
- Hovering over the zoom buttons in secondary detail panes could lose
the zoom mode highlight.
Closes #202

Fix two issues with the zoom mode buttons in detail panes:

---

NGCHM/WebContent/javascript/NGCHM_Embed.js

This was prompted by a request from Tod, and supports the mbatch projects.

Add onload parameter for embedNGCHM (sets onload in emebedded iframe)

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/css/NGCHM.css
NGCHM/WebContent/javascript/DetailHeatMapManager.js
NGCHM/WebContent/javascript/MatrixManager.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/RecreatePanes.js
NGCHM/WebContent/javascript/UserHelpManager.js
NGCHM/src/mda/ngchm/util/NGCHM_AppGenerator.java
NGCHM/src/mda/ngchm/util/NGCHM_Widgetizer.java

Adds a splash screen to the initial browser window.
Makes the loading messages more prominent.
Implements smooth transitions for splash screen display, displaying
loader messages, and showing the loaded NG-CHM.

Add an initial splash screen, a more prominent loader screen, transitions

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/javascript/Tour.js

Open links from guided tour in a new tab

---

NGCHM/WebContent/javascript/UserHelpManager.js
NGCHM/WebContent/javascript/custom/custom.js

Increase version number for linkouts changed in 43ff6d8, uncommented version for Antibody RRID

Changes about linkout version numbers

---

NGCHM/WebContent/javascript/Linkout.js

Bug fix: #325

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/javascript/ColorMapManager.js
NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/DetailHeatMapEvent.js
NGCHM/WebContent/javascript/Drawing.js
NGCHM/WebContent/javascript/Linkout.js
NGCHM/WebContent/javascript/MatrixManager.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/PaneControl.js
NGCHM/WebContent/javascript/PdfGenerator.js
NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
NGCHM/WebContent/javascript/UserHelpManager.js
NGCHM/WebContent/javascript/UserPreferenceManager.js

Initial restructuring efforts.

Restructure part 1

---

NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js

Another bug detected by strict mode.

Bugfix: Define various boxXYWH variables when drawing ribbon mode

---

NGCHM/WebContent/javascript/DetailHeatMapDisplay.js

Fix a pair of undeclared local variables.

Declare local scale variable

---

NGCHM/WebContent/javascript/UserPreferenceManager.js

Import DET into UserPreferenceManager.js

---

NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/DetailHeatMapEvent.js
NGCHM/WebContent/javascript/Linkout.js
NGCHM/WebContent/javascript/MatrixManager.js
NGCHM/WebContent/javascript/PluginInstanceManager.js
NGCHM/WebContent/javascript/SearchManager.js
NGCHM/WebContent/javascript/SearchState.js
NGCHM/WebContent/javascript/SummaryDendrogram.js
NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
NGCHM/WebContent/javascript/UI-Manager.js
NGCHM/WebContent/javascript/UserHelpManager.js

I'm working my way through the showstopper bugs James recently submitted.

Show stopper fixes

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/DetailHeatMapEvent.js
NGCHM/WebContent/javascript/DetailHeatMapManager.js
NGCHM/WebContent/javascript/Linkout.js
NGCHM/WebContent/javascript/MatrixManager.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/PaneControl.js
NGCHM/WebContent/javascript/PluginInstanceManager.js
NGCHM/WebContent/javascript/RecreatePanes.js
NGCHM/WebContent/javascript/SearchManager.js
NGCHM/WebContent/javascript/UI-Manager.js
NGCHM/WebContent/javascript/UserHelpManager.js
NGCHM/WebContent/javascript/UserPreferenceManager.js
NGCHM/WebContent/javascript/custom/custom.js

More bug fixes

---

NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/DetailHeatMapManager.js

A collection of small bug fixes.

Yet more bug fixes

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/css/NGCHM.css
NGCHM/WebContent/javascript/API.js
NGCHM/WebContent/javascript/ColorMapManager.js
NGCHM/WebContent/javascript/Config.js
NGCHM/WebContent/javascript/Customization.js
NGCHM/WebContent/javascript/DetailHeatMapEvent.js
NGCHM/WebContent/javascript/DetailHeatMapViews.js
NGCHM/WebContent/javascript/Linkout.js
NGCHM/WebContent/javascript/MatrixManager.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/PaneControl.js
NGCHM/WebContent/javascript/PdfGenerator.js
NGCHM/WebContent/javascript/UI-Manager.js
NGCHM/WebContent/javascript/UserHelpManager.js
NGCHM/WebContent/javascript/UserPreferenceManager.js
NGCHM/WebContent/javascript/custom/custom.js
NGCHM/src/mda/ngchm/util/NGCHM_Minimizer.java

Note: I have not addressed the keyboard navigation issues in this pull request.
Note: increment version number immediately prior to merging

Various bug fixes and small enhancements

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/javascript/CompatibilityManager.js
NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/DetailHeatMapEvent.js
NGCHM/WebContent/javascript/FlickManager.js
NGCHM/WebContent/javascript/Linkout.js
NGCHM/WebContent/javascript/PdfGenerator.js
NGCHM/WebContent/javascript/UI-Manager.js
NGCHM/WebContent/javascript/UserPreferenceManager.js

Fixes for additional show-stopper issues.
Includes version bump so I don't forget at merge time.

More showstopper fixes

---

NGCHM/WebContent/css/NGCHM.css
NGCHM/WebContent/javascript/CompatibilityManager.js
NGCHM/WebContent/javascript/Linkout.js
NGCHM/WebContent/javascript/PaneControl.js

Add a few minor enhancements:
- Add "Download all matrix data to file' matrix menu entry
- Hide expander button in collapsed panes (in response to comment by Thomas)
- Rename 'Expand' menu entry to 'Uncollapse' (in response to comment by Thomas)

Minor enhancements

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/css/NGCHM.css
NGCHM/WebContent/javascript/DetailHeatMapEvent.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/PluginInstanceManager.js
NGCHM/WebContent/javascript/custom/custom.js

Fixes two show-stoppers and another one.

Additional bug fixes

---

NGCHM/WebContent/javascript/CompatibilityManager.js

Release NG-CHM Viewer version 2.2.4.0.

Release NG-CHM Viewer version 2.24.0

---

.github/workflows/build-NGCHMSupportFiles.yml
NGCHM/WebContent/javascript/MatrixManager.js

Bug fix for 2.24.0 to correct "&collectionHome=" problem, plus other recent changes to the Github actions.

Bug fix for 2.24.0 - creating 2.24.1

---

.github/workflows/build-NGCHMSupportFiles.yml
.github/workflows/create-tag-and-build-NG-CHM-Artifacts.yml
Dockerfile
NGCHM/build_ngchmApp.xml

This also removes 3 old versions of closure-compiler.jar.

Update closure-compiler, requires jdk 11

---

NGCHM/WebContent/javascript/custom/custom.js

Add some linkouts to LinkedOmics website.

Add linkouts to LinkedOmics site

---

NGCHM/src/mda/ngchm/datagenerator/HeatmapDataGenerator.java
NGCHM/src/mda/ngchm/datagenerator/ImportConstants.java
NGCHM/src/mda/ngchm/datagenerator/ImportData.java
NGCHM/src/mda/ngchm/datagenerator/ShaidyRMapGen.java

This PR allows for an initial panel layout from the NGCHM R code in corresponding PR https://github.com/MD-Anderson-Bioinformatics/NGCHM-R/pull/75. More details are in that PR.
I verified a map generated with ShaidyMapGen.jar built from this PR and NGCHM R version 1.0.4 (our current CRAN release, which does not include panel initialization) builds and opens in the viewer w/o errors.
See also testing performed section in https://github.com/MD-Anderson-Bioinformatics/NGCHM-R/pull/75.

Java changes for multi-panel from R feature request

---

NGCHM/WebContent/css/NGCHM.css
NGCHM/WebContent/javascript/CompatibilityManager.js
NGCHM/WebContent/javascript/DetailHeatMapEvent.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/UI-Table.js
NGCHM/WebContent/javascript/UserPreferenceManager.js

A handful of unrelated fixes:
- Removed a no longer used function UTIL.reverseObject
- Made some properties common in maps in the TCGA compendium so that they don't cause errors if the data is uploaded to the GUI builder
- Totally reworked how covariate bar clicks work.
- Added calls to startChange on keydown events so that the Apply/Reset buttons become active immediately.

Various fixes

---

NGCHM/WebContent/chm.html
NGCHM/WebContent/css/NGCHM.css
NGCHM/WebContent/javascript/ColorPalettes.js
NGCHM/WebContent/javascript/CommandMode.js
NGCHM/WebContent/javascript/CommandParser.js
NGCHM/WebContent/javascript/CovariateCommands.js
NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/ExecCommand.js
NGCHM/WebContent/javascript/HeatMapCommands.js
NGCHM/WebContent/javascript/Linkout.js
NGCHM/WebContent/javascript/MatrixManager.js
NGCHM/WebContent/javascript/NGCHM_Util.js
NGCHM/WebContent/javascript/SearchCommands.js
NGCHM/WebContent/javascript/SearchManager.js
NGCHM/WebContent/javascript/SearchState.js
NGCHM/WebContent/javascript/UI-Manager.js
NGCHM/WebContent/javascript/UserHelpManager.js
NGCHM/WebContent/javascript/UserPreferenceManager.js
NGCHM/WebContent/javascript/custom/custom.js
NGCHM/WebContent/javascript/lib/lexer/lexer-master/LICENSE
NGCHM/WebContent/javascript/lib/lexer/lexer-master/README.md
NGCHM/WebContent/javascript/lib/lexer/lexer-master/bower.json
NGCHM/WebContent/javascript/lib/lexer/lexer-master/component.json
NGCHM/WebContent/javascript/lib/lexer/lexer-master/lexer.js
NGCHM/WebContent/javascript/lib/lexer/lexer-master/package.json

Add the ability to execute a variety of "command line" style commands to custom.js files and to an interactive command window.
See the commit message of the last commit (https://github.com/MD-Anderson-Bioinformatics/NG-CHM/commit/5a92f2edecbb45fe3772593bc5bdbfc00427c6e5) for more details.

Initial implementation of "command line" style commands.

---

NGCHM/WebContent/javascript/Config.js
NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
NGCHM/WebContent/javascript/DetailHeatMapEvent.js
NGCHM/WebContent/javascript/DetailHeatMapManager.js
NGCHM/WebContent/javascript/HeatMapRep.js
NGCHM/WebContent/javascript/Linkout.js
NGCHM/WebContent/javascript/MatrixManager.js
NGCHM/WebContent/javascript/PluginInstanceManager.js
NGCHM/WebContent/javascript/SearchManager.js
NGCHM/WebContent/javascript/SearchState.js
NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
NGCHM/WebContent/javascript/UI-Manager.js
NGCHM/WebContent/javascript/UserPreferenceManager.js

A handful of small changes.
- Moved MMGR.isRow to MAPREP.isRow.
- Removed an unused parameter to showViewerSaveNotification
- Changed the default api endpoint from "" to "api" (discussed with @ChrisWakefield )
- Reduced console output from commands executed from custom.js
- Fixed a bug when selections were cleared before summary map dendrograms were created.

Various small bugfixes and changes
