- NGCHM/WebContent/chm.html
- NGCHM/WebContent/javascript/Config.js
- NGCHM/WebContent/javascript/Customization.js
- NGCHM/WebContent/javascript/MatrixManager.js
Moves API location to a location separate from NGCHM viewer, so
that it simplifies writing rules for front-end proxies etc.
Define that location in this small static file so that it can be
changed easily.  (e.g. by having proxy redirect to a customized file.)
Also include location of linkout customization script here as well.
> Enable easy configuration of server API location

- NGCHM/src/mda/ngchm/datagenerator/ShaidyRMapGen.java
ShaidyMapGen was crashing before it could output error messages.  This prevents the crash so the
error messages can be output.
> Don't crash on bad meta data.

- NGCHM/WebContent/javascript/ColorMapManager.js
- NGCHM/WebContent/javascript/Dendrogram.js
- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/MatrixManager.js
This pull request includes:
- some fixes to illegal data accesses in vertical ribbon mode
- fixes to undeclared local variables
- various changes to enhance drawing speed, including:
- label width memoization
- label blanking during redraw
- parsing dendrogram data once
- using a single context for drawing selections.
Depending on the particular circumstances, drawing can be a factor of 2-3 times faster based on my tests with Chrome.
> Big fixes and drawing speed ups

- NGCHM/WebContent/javascript/UserHelpManager.js
This feature is intended for use by a document that includes
the NGCHM in an iframe:
- The enclosing window includes a secret nonce as an extra parameter
in the NGCHM URL  ....?nonce=value&...  Any random value will suffice.
- The enclosing window posts a message to the iframe including the nonce:
{ nonce: value, override: 'ShowMapDetails' }
- Instead of displaying map details itself, the NgChm will post messages
to the enclosing window.  The message will include the nonce as well
as details about the current pixel.
> Enable enclosing window to request map details be posted to it.

- NGCHM/WebContent/javascript/CompatibilityManager.js
- NGCHM/WebContent/javascript/Customization.js
- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/MatrixManager.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/PaneControl.js
- NGCHM/WebContent/javascript/PdfGenerator.js
- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
- NGCHM/WebContent/javascript/UserHelpManager.js
- NGCHM/build_ngchmApp.xml
- NGCHM/src/mda/ngchm/datagenerator/HeatmapDataGenerator.java
New NGCHM Project items fixed in this branch:
PT #171882807: Eliminate warning messages in ngchmApp widget builder process.
PT #171882807: Eliminate warning messages in ngchmApp widget builder process.
PT #171937256: Scatterplot throws errors on drawing selections on summary panel when panel not present
PT #171937316:  Replace alert popups in panels code with error message boxes OR console messages
PT #171997994: sValues summation error for large maps with continuous covariates that are missing labels.
PT #172058160: Viewer PDF -  Give user indication when PDF creation is halted due to lack of open summary and detail panels
PT #171976784:  Standalone Viewer - Loading a new heat map in the standalone or other viewers should reset view to standard view of Summary panel on the left and …
> NgChm Viewer Release 2.17.2

- NGCHM/WebContent/chm.html
- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/CompatibilityManager.js
- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/MatrixManager.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/SearchManager.js
- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
Pivotal Tracker items covered by this pull request"
#172607456: Search dialog DOM elements drawing differently in Firefox and Builder.
#172609983: State tracking on search drop down check boxes needs to be able to handle 2 searches (row and col)
#172672555: Covariate search dropdown checkboxes showing behind divider bar
#172672580: Shorten covariate label length displayed in search covariate dropdown checkbox
#172672598: Modify search to allow for user-constructed expressions with two operators.
#172687319: Selection marks on summary side being drawn too wide
#172717454: Selection mark and top item line canvases being placed off the viewable area for small maps
#172717472: Summary selection marks drawn on top of top items arrows
> PTs: #172607456, #172609983, #172672555, #172672580, #172672598,

- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/UserHelpManager.js
Added several features to the gear dialog for plugins. These changes
are in Linkouts.js:
- Checkboxes for selection of discrete covariates
- Range input boxes for selection of continuous covariates
- Help tooltips
- Statistical test for mean
Also made other changes that are not quite part of the gear dialog UI:
- Color map sent to plugins (Linkouts.js)
- System alert if groups have < 2 members (Linkouts.js)
- statistical tests will crash if < 2 members
- Show labels in NGCHM when sent from plugins (NGCHM_Util.js)
- bug fix
- Send labels to plugins when clicked on (DetailHeatMapDisplay.js)
- bug fix
- Optional delay for showing tooltip (UserHelpManager.js)
- so that when user hovers over '?', the tooltip can show up
right away
> Add covariate selection & mean test to gear dialog

- NGCHM/WebContent/javascript/Linkout.js
Bug fix for selecting continuous covariates in the gear dialog
when there are missing values in the covariate. 
Without this fix, if there are missing values in the covariate bar, users are unable to select ranges to pass to the plugins.
> Fix bug for missing values in cont covariate

- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/Dendrogram.js
- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
This commit implements the RESET button on the Gear Dialog, fixes
some bugs, and makes code and UI improvements on the Gear Dialog.
Most of the changes are in Linkouts.js, with two exceptions in
Dendogram.js and NGCHM_Util.js noted below, and some changes to
the css in NGCHM.css.
Bug fixes:
- Selection of Scatter Plot points by clicking dendograms
- this is the change in Dendogram.js
- Disallows selection of non-numeric covariates for Coordinates in
Gear Dialog
- Selection of points between two Scatter Plots
Gear Dialog UI improvements
- In choosing groups from discrete covariates, limit the height of
the selection box and allow for scrolling (sometimes the list of
discrete covariates is very long).
- part of this is the change in NGCHM_Util.js. This change of
the wheel event listener was …
> Implement RESET button & fix bugs

- NGCHM/WebContent/javascript/CompatibilityManager.js
- NGCHM/src/mda/ngchm/datagenerator/GalaxyMapGen.java
This is the 2.17.6 Viewer ready for testing.  The only changes from Mary's #37 pull request are changes to set the version number for the Viewer (2.17.6) and Galaxy (2.11.3).  The Master can be tagged 2.17.6 as soon as it is merged.
> 2.17.6 Viewer ready for testing

- NGCHM/src/mda/ngchm/datagenerator/HeatmapDataGenerator.java
This attempts to fix a bug in which when the -FULLPDF flag is given to GalaxyMapGen.jar, the missing data values are set to RGB_BLACK instead of being set to the 'missing' value specified in heatmapProperties.json.
Specifically, the command 
```bash
java -cp GalaxyMapGen.jar mda.ngchm.datagenerator.HeatmapDataGenerator ./heatmapProperties.json -FULLPDF
```
would produce a PDF file in which the missing values were always black, instead of the value specified as 'missing' in the color map. Here is a snippet of the heatmapProperties.json file for reference:
```json
"color_map": {
"type": "linear",
"colors": ["#0000ff","#ffffff","#ff0000"],
"thresholds": [0,1,2],
"missing": "#b3b3b3"
}
```
These missing values are set to MAX_VALUES in InputFile.java (I think). For reference here's one …
> Potential bug fix for missing color always set to black in PDF

- NGCHM/WebContent/javascript/UserHelpManager.js
Recent changes renamed the "container" lelement to "ngchmContainer"
and somehow the reference to "container" in UserHelpManager.js was lost.
This patch simply gets a reference to the "ngchmContainer" element.
> Fix issue with Plugin Help not appearing

- NGCHM/WebContent/javascript/Linkout.js
Initial implementation used predictable nonces to simplify
development.  However, that's a huge security problem that
effectively defeats their purpose.  This patch uses crypt.getRandomValues
to generate unpredictable values.
> Create unpredictable nonces

- NGCHM/WebContent/javascript/CompatibilityManager.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
- NGCHM/src/mda/ngchm/datagenerator/GalaxyMapGen.java
This production release branch contains 2 fixes for items for a new 2.18.2 release that were discussed at last Thursday's meeting: 
#173967975: REFLECT site having issues with covariate bar display on maps with just 2 columns
#174070556: GUI Builder - Get Thumbnail Image button not working in Chrome or Firefox
> 2.18.2 Release - PT items: #74070556 and #173967975

- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/CompatibilityManager.js
- NGCHM/WebContent/javascript/UserPreferenceManager.js
- NGCHM/src/mda/ngchm/datagenerator/GalaxyMapGen.java
PT #174869184:  Prefs panel location for embedded NGCHM.  
Notes:  The original code and Chris' changes have been incorporated. In addition, the original fix only solved the top/bottom sizing and placement of the prefs panel. The left/right placement was set to 0 right and 0 left, respectively. This had the panels being drawn off the NGCHM widget on embedded maps. Now the left right placement has also been modified to place the prefs panel inside the NGCHM widget.
> Insilico prefs sizing fix

- NGCHM/WebContent/javascript/custom/custom.js
Add the metabolite and compound link outs to the default link outs.
For the type codes, I changed the "bio" category (the second field) to either "metabolite" or "compound".
> Add a variety of linkouts for metabolite and compound identifiers

- NGCHM/WebContent/javascript/Linkout.js
This is the part of the code that fills in the gear dialog with any existing previous values (so that if the user clicked 'APPLY', closed the gear dialog, and reopened the dialog, the previously applied values are automatically filled it.)
Suggesting changing this equality so that '1.0' and 1.0 are regarded as equal. 
Without this change either plugin developers will have to set numeric values to be strings, or further changes will have to be made to the NGCHM code to ensure '1.0' is regarded as equal to 1.0 and previously applied numeric values are properly initialized.
> Change strict to loose equality for gear init

- NGCHM/WebContent/javascript/Linkout.js
I think the root cause of https://github.com/MD-Anderson-Bioinformatics/ScatterPlotPlugin3D/issues/31 is that if selections have been made on one scatter plot, and then a second scatter plot is opened, that second scatter plot has nothing selected. Scrolling over that second scatter plot then highlights the point under the mouse, which is then posted to all of the other panels, effectively unselecting everything else.
By passing the selected labels to the plugin upon initialization, the plugin can use them to select those labels from the start, and its selections will be in sync with the other panes from the start. Initial testing suggests this corrects https://github.com/MD-Anderson-Bioinformatics/ScatterPlotPlugin3D/issues/31. 
I think this same problem existed in the 2D scatter plot, …
> Send selected labels to plugins upon initialization

- NGCHM/WebContent/javascript/custom/custom.js
Heat map creator can add a species property, which will be used in
link outs that include the species in the url.
Tested with "Homo_sapiens" (default) and "Mus_musculus".
> Allow heat map creator to specify a species for link outs that use it.

- NGCHM/WebContent/javascript/Linkout.js
Added a new function to the vanodi API. This function allows plugins to request a property from the NGCHM. These are properties embedded in the NGCHM at build time, for example via the function chmAddProperty() from [NGCHM-R](https://github.com/MD-Anderson-Bioinformatics/NGCHM-R).
(There are several commits, but it's only a tiny bit of Linkouts.js that is changed).
> Add new function: vanodiSendProperty()

- NGCHM/WebContent/chmHelp.html
- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/CompatibilityManager.js
- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/DetailHeatMapEvent.js
- NGCHM/WebContent/javascript/DetailHeatMapManager.js
- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/NGCHM_Embed.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/PdfGenerator.js
- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
- NGCHM/WebContent/javascript/UserHelpManager.js
- NGCHM/WebContent/javascript/UserPreferenceManager.js
- NGCHM/src/mda/ngchm/datagenerator/GalaxyMapGen.java
Merge 2.19.5 Version bug fixes and enhancements to master branch.
This request contains the following Pivotal Tracker items:
PT: #176854565 - Summary drag select not working.
PT: #176854607 - When in Horiz or Vertical sub-ribbon view, the ribbon buttons do not draw correctly when hovered over.
PT: #176803641 - Shift-Drag in summary pane causes error in console.
PT: #176825189 - If only detail pane on map is collapsed, pdf font size defaults to -2.
PT: #176825270 - If create pdf when only detail pane is collapsed, pdf creation fails silently with error in console.
PT: #176824830 - Detail panes past first two come out blank for some maps in portrait mode.
PT: #176824325 - Parts of some labels for covariates off side of page in portrait mode with histograms.
PT: #176803488 - Zooming out on …
> PTs: #173952827, #176854565, #176854607, #176803641, #176825189,

- NGCHM/WebContent/chm.html
- NGCHM/WebContent/javascript/CompatibilityManager.js
- NGCHM/WebContent/javascript/DetailHeatMapEvent.js
- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/NGCHM_Embed.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/PdfGenerator.js
- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
This pull request contains the fixes for the bugs from the latest round of 2.19.x testing.  I have also documented fixes that were added to the NGCHM GUI Builder project as there were a number of fixes to the builder this round.  Some of these, but not all, being fixes made in Viewer code.  The Viewer version has been moved to 2.19.7 and the builder to 2.19.4 after these modifications.
The fixes for all of the bugs in the latest round of testing are as follows:
PT #176825189: If only detail pane on map is collapsed, pdf font size defaults to -2.
PT #176803488: Zooming out on detail panes not working correctly.
PT #177100513: If invalid value selected for font size in PDF Generation dialog, error message pushes other fields off visible area of popup.
PT #177098084: NGCHM Thumbnail …
> PTs: #176825189, #176803488, #177100513, #177100342, #177098084, #177164355, #177168626, #177162760, and #177169016

- NGCHM/WebContent/javascript/CompatibilityManager.js
- NGCHM/WebContent/javascript/DetailHeatMapEvent.js
- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/PaneControl.js
- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
Contains the following fixes:
PT #177308891: "Set selection as detail view" on map detail should set the detail pane where the menu option was used to the selection rather than setting the pane selected as primary to the selection.
PT #177372993: Summary map does not expand into a maximized panel when not full height
Viewer Version updated to 2.19.8
These changes also checked in, via widget, to GUI Builder with the version of the builder updated to 2.19.5
Builder also received the following fix:
PT #177311041: GUI Builder - Map Description field should allow as many types of commonly used characters as possible without allowing build to break instead of just alphanumeric and a few special characters.
> PTs #177308891 and #177372993

- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/MatrixManager.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
This sequence of commits allows server maps to be specified by 'name' using a URL of the form ".../chm.html?name=the.name".
It requires the web server to implement the GetMapByName API call for translating names to a mapid.  When (if) the viewer gets the mapId, it loads the mapConfig and mapData files using the mapId.
This feature was requested by the stat analysts so improve their interactions with collaborators.
> Specify maps by name

- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/UserHelpManager.js
- NGCHM/WebContent/javascript/custom/custom.js
This pull request is for a single Pivotal tracker item (PT #177796443: Several icons missing in "Installed Plug-ins" Information panel).  I believe we want to merge this small change into the Master before tagging the new 2.20.1 version but will leave that to the group to decide.
The following is a list of changes made in this fix:
1. New Ideogram viewer logo URL added. (custom.js)
2. New Cancer Genome Atlas logo URL added (custom.js)
3. New Mave DB logo URL added. (custom.js)
4. New RRID logo URL added. (custom.js)
5. For plugins without a logo, I added bold font to the hyperlink that appears in lieu of a logo (UserHelpManager.js)
6. The background color of the list display was changed from white to gray because the logos for QuickGO and Depmap Portal are white with a transparent …
> PT #177796443: Several icons missing in "Installed Plug-ins" Information

- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/PaneControl.js
- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
One more item to go along with adding 3D scatterplot to the Viewer.  Until the scatterplot features work with maps that contain gaps, we will put up a message that the plots are unavailable for maps containing gaps.
> PT #177949803:  Add message indicating that scatterplot features are unavailable for maps with gaps

- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/ColorMapManager.js
- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/DetailHeatMapEvent.js
- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/MatrixManager.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/PdfGenerator.js
- NGCHM/WebContent/javascript/SearchManager.js
- NGCHM/WebContent/javascript/SelectionManager.js
- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
- NGCHM/WebContent/javascript/UserPreferenceManager.js
Allows test frameworks to more easily determine selected labels.
Instead of modifying the styles of selected labels, add a secondary class to them and use that to determine colors.
The central modifications are to: 
- SelectionManager.js
- DetailHeatMapDisplay.js
- NGCHM.css
A lot of incidental changes caused by requiring the current data layer to be get/set by functions.  Ensures that current data layer can't be changed without updating selection colors.
I've tested the following:
- Heat maps with non-default selection color in first (default) data layer
- Changing selection color in preferences dialog
- Toggling between layers with different selection colors.
There is a section of code in DetailHeatMapDisplay for setting the colors of labels with text == "<".  I couldn't figure out what …
> Use class inSelection to indicate selected labels

- NGCHM/Documentation/DragAndDrop.md
- NGCHM/WebContent/chm.html
- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/custom/custom.js
Adds ability to drag-and-drop a plugin onto the NG-CHM viewer at runtime.
- Allows users to add their own plugins.
- Simplifies plugin development and testing.
> Drag and drop

- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
Improve performance of drawSelections when there many searchBoxes on both axes.  Test case found by James was taking tens of seconds to redraw the screen and freezing the browser window for the duration.
This pull request addresses most cases.
There is still an issue in an extreme case (whole map displayed in the detail pane(s), with a large number of search boxes on both axes).
> Speed up draw selections

- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/MatrixManager.js
In order to deal with issues such as [PathwayMapper #17](https://github.com/MD-Anderson-Bioinformatics/pathway-mapper/issues/17), this pull request adds a function similar to `getAccessWindow`, but returning a Promise that resolves when all needed tiles for the window are available in the tileCache.
The existing `getAccessWindow` was designed to return a summary result for `getValue` if the needed tile is not available in cache. This was done to optimize drawing of large maps. Example usage:
```js
let accessWindow = NgChm.heatMap.getAccessWindow(win)
let val = accessWindow.getValue(rowIdx, colIdx) // <-- summary value returned if needed tile not in cache
```
However for plugins doing calculations such as mean, t-test, etc, the actual value is required. The newly added function …
> Add Promise-based getAccessWindow

- .github/workflows/build-artifacts.yml
This pull request adds a GitHub action to build and push artifacts to the [NGCHMSupportFiles](https://github.com/MD-Anderson-Bioinformatics/NGCHMSupportFiles) project.
The action is triggered by new releases, and with the following main steps:
- Checks out release tag
- Builds ShaidyMapGen.jar
- Builds ngchmWidget-min.js
- Checks out  the NGCHMSupportFiles project
- Adds ShaidyMapGen.jar and ngchmWidget-min.js to  the NGCHMSupportFiles project
- Updates version number of NGCHMSupportFiles project to match release tag
- Commits and pushes updates back to  the NGCHMSupportFiles project
- Makes release of NGCHMSupportFiles project for new version
The Action is configured to use the DQS-Dev-BCB service account.
> Use Action to build NGCHMSupportFiles artifacts

- NGCHM/WebContent/chm.html
- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/PaneControl.js
- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
This pull request fixes a variety of small buglets that I encountered when developing / testing the tour and
splash screen feature branch.
The panel sizing bug (7f7bc04) was causing the tour to highlight an excessively long section of the screen.  Without the tour, it's easiest to see its effects using the inspect feature of the dev tools debugger.
> Fix buglets

- NGCHM/WebContent/javascript/RecreatePanes.js
This is really a question for Mary.
Was there a specific reason for replacing the ngChmContainer element in RecreatePanes?
My initial thoughts are that we want to keep the current ngChmContainer element in case there have been any changes to its properties etc. since the map being loaded was saved.
I tried this patch with save files containing a single panel as well as save files containing multiple panels. All appears fine.
> Replace only the children of NgChm.UTIL.containerElement

- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/DetailHeatMapEvent.js
- NGCHM/WebContent/javascript/DetailHeatMapManager.js
- NGCHM/WebContent/javascript/Drawing.js
- NGCHM/WebContent/javascript/MatrixManager.js
- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
The browser can remove access to a WebGL context at basically any time.
When the context is removed, any WebGL objects for that context are
destroyed.
Until the context is restored, no WebGL functions for that context can be
used.
After the context is restored, no previous WebGL objects can be used.
To facilitate handling of the context loss and restore events and simplify
our use of WebGL, this patch creates and uses a common GLManager object
for each canvas.  GLManager is implemented in Drawing.js.
> Handle WebGL context loss and restore events

- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/DetailHeatMapEvent.js
- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/PaneControl.js
- NGCHM/WebContent/javascript/UserHelpManager.js
Commit 0592b50 introduced a simpler way of determining the correct image
to use for the zoom mode buttons in the normal, hover, and selected states.
However, that broke the Widgetizer.  The Widgetizer requires images to
have full pathnames, which it converts to 'data:' URLs that are included
in the widget javascript code to make it standalone.
This patch adds a simple table lookup to convert from image names to
image paths, thus allowing the Widgetizer to do its conversions, which
also achieving the goals of the original patch.
At the same time, I noticed that there are many URLs that are included multiple times in the source code.  Each duplication unnecessarily expands the size of the widget.  The additional commits address the worst of those duplications.
The minified widget from …
> Fix widgetized image issues

- NGCHM/src/mda/ngchm/util/NGCHM_AppGenerator.java
- NGCHM/src/mda/ngchm/util/NGCHM_Widgetizer.java
The standalone application ngChmApp.html generates an error on initial page load.
The inline script needs to be appended after the minimized Javascript. Use same
solution that the Widgetizer uses.
> Bugfix: append inline script in AppGenerator

- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
Set the size of the WebGL viewport for the detail pane each time the WebGL context is used.
The size of the viewport changes when switching between the different zoom modes.
Fixes #215.
> Set Detail Pane Viewport Every Time

- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/Dendrogram.js
- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/DetailHeatMapEvent.js
- NGCHM/WebContent/javascript/DetailHeatMapManager.js
- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/MatrixManager.js
- NGCHM/WebContent/javascript/PaneControl.js
- NGCHM/WebContent/javascript/PdfGenerator.js
- NGCHM/WebContent/javascript/RecreatePanes.js
Save dendrogram zoom levels and restore them on reload.
Make per-detail-map versions of several variables that were global across
all detail panels. Specifically:
- dendrogram zoom initialization status,
- whether a detail map should be resized on next redraw, and
- timeout to detail map redraw event.
Avoid using NgChm.DMM.primaryMap to access properties that are really
global across all detail maps (e.g. current data layer).
> Fix restoration of detail panels including dendrogram zoom levels

- NGCHM/WebContent/javascript/custom/custom.js
Incidentally, this leaves 30 instances of "http:" for something like 10 or 11 sites/linkouts.  These were not changed based on recent testing in the browser and finding that https did not work for those links.
> Updated cbio linkout and changed many links to use https.  Fixes #235

- NGCHM/WebContent/chm.html
- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/UserHelpManager.js
This pull request makes the following changes to the 'NG-CHM Plug-in Information' ('Plug-in Help...') dialog:
- Make plug-in name link to website
- Make corresponding change to table header text
- Make only the close button in the footer clickable to close dialog (instead of whole footer)
- Change cursor to pointer on hover over close button and tabs in table
> Plugin help table links

- NGCHM/WebContent/javascript/UserHelpManager.js
- NGCHM/WebContent/javascript/custom/custom.js
This addresses several issues found with the 'NG-CHM Plug-in Information' ('Plug-in Help...') dialog:
- Addresses missing image issue in Active Plug-ins tab
- Updates link for CIViC
- Adds link for MetabolomicsWorkbench
- Manually alphabetize plugins
> Plugin help fixes

- NGCHM/WebContent/javascript/custom/custom.js
Add a link out to the UCSC genome browser for labels of type "bio.genome.position".
The genome browser database to use defaults to "hg38" but can be changed by setting the heat map property "bio.ucsc.browser.db" to the desired database name.
> Add bio.genome.position and UCSC Genome Browser linkouts

- NGCHM/WebContent/javascript/NgChm.js
- NGCHM/src/mda/ngchm/util/NGCHM_Minimizer.java
- NGCHM/src/mda/ngchm/util/NGCHM_Widgetizer.java
Remove hard-coding of jspdf.min.js from Widgetizer/Minimizer in favor of existing  comment.
Add ability to remove code between BEGIN EXCLUDE and END EXCLUDE comments in javascript code.
Use that ability to remove development tools from NgChm.js from compiled code (widget, standalone viewer, etc.)
> Compile time changes

- NGCHM/WebContent/javascript/Linkout.js
The key pieces to this bug fix are:
1. Move the declaration of `win` to inside the for loop
- The bug was caused by values of 'win' in later iterations of the loop being used in `getAccessWindowPromises.push(heatMap.getAccessWindowPromise(win))`. By moving the declaration to inside the loop, we are effectively using a different 'win' for each iteration.
2. Change the 'win' in the `accessWindows.forEach()` to be the 'win' of the specific 'accessWindow' of the forEach().
Note: I was initially concerned this bug was also present in `getSummaryStatistics()`. However, 1) 'win' is already declared inside the relevant for loop in that function (see near [line 1288 of Linkouts.js](https://github.com/MD-Anderson-Bioinformatics/NG-CHM/blob/main/NGCHM/WebContent/javascript/Linkout.js#L1288)), and 2) …
> Bug fix: GRAB not returning averages (#329)

- NGCHM/WebContent/javascript/PdfGenerator.js
I made these in the first restructure patch.
> Fix two typos setting the onclick handlers in PdfGenerator.js

- NGCHM/WebContent/javascript/NgChm.js
If, and it is a big if, the modules are imported in the order that minimizes the number of such out-of-order imports, this is equivalent to determining the minimum number of edges that must be removed to convert the module graph into an acyclic graph.
In general, this is the minimum feedback arc set problem in graph theory and it is NP-hard.  However, all the complexity involved is in determining the optimal order of imports (there are also other approaches).
I think we can assume that the import order is already at least a very good approximation to the best order and good enough for our needs.  And a lot simpler to implement.
The code is included in a region of NgChm.js that will be excluded from the production code by the compiler.
> Count and trace modules imported before they are defined

- NGCHM/WebContent/javascript/CompatibilityManager.js
- NGCHM/src/mda/ngchm/util/NGCHM_Widgetizer.java
This re-adds the one-line fix that didn't get pulled from 2.22.2 to main.  (My mistake.)  The 2.22.2 commit could not be merged or cherry-picked without conflicts due to main's extensive changes.  
I also introduced version 2.23.0 indicating a development version, as we agreed to increment the number with each interim version.
> Re-add fix for issue 324.  Set to odd (development) version

- NGCHM/WebContent/javascript/Dendrogram.js
- NGCHM/WebContent/javascript/DetailHeatMapEvent.js
- NGCHM/WebContent/javascript/DetailHeatMapManager.js
This is a start towards fixing a bug that was made in commit c5f05b5bcca9a on 2019-07-11.  The code was committed by Mark Stucky but it was my code. (At this time, Mark was collecting all the patches etc. and then committing them to github in batches.)
The commit concerned was when I totally rewrote the dendrogram code.
The previous code was setting the 'DDR.subDendroMode' global variable to row or column if the user clicked on a summary view dendrogram branch. The replacement code never set the variable.
The variable has been tested in DetailHeatMapDisplay ever since, failing every time.  The test is supposed to select row or column scaling on one axis only when the user zooms all the way out in subDendro mode. It wasn't. (Both axes were being scaled, as when zooming all the way out in …
> BUGFIX: Detect subDendroMode again

- NGCHM/WebContent/javascript/Customization.js
- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/DetailHeatMapEvent.js
- NGCHM/WebContent/javascript/MatrixManager.js
- NGCHM/WebContent/javascript/SearchManager.js
- NGCHM/WebContent/javascript/SelectionManager.js
- NGCHM/WebContent/javascript/UI-Manager.js
- NGCHM/WebContent/javascript/UserHelpManager.js
Third set of restructure changes.  This set comprises two very small rearrangements and a larger one.  The first two involve moving heat map initialization code from immediately after the mapConfig JSON structure is received, inside MatrixManager, which may happen before the map is fully initialized, to within an Event_INITIALIZED handler in UI-Manager.  The event is handled as soon as it should be.
The third involves leaving all the generic code for help dialogs etc. in UserHelpManager but moving the code for creating dialogs for specific areas into the modules for those areas.  E.g. moving the code for creating the detail map popups into the detail map modules.  Currently, there are many circular dependencies between the modules for the specific areas, the UHM, and all the modules for …
> Restructure part 3

- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/DetailHeatMapManager.js
- NGCHM/WebContent/javascript/SummaryDendrogram.js
- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
- NGCHM/WebContent/javascript/UI-Manager.js
- NGCHM/WebContent/javascript/UserHelpManager.js
Updates the behavior of the ribbon mode dendrogram selection as we discussed.
Tracks whether each detail view's ribbon mode focus area is a dendrogram selection. Initially false. Set to true if the user selects a dendrogram branch on the summary map.  Cleared if the user uses keyboard navigation to change the focus area (and displays a popup allowing the user to reset the focus region if desired).
Also used to update dendrogram ribbon mode highlight when switching between detail maps or when restoring saved maps.
Fixes issue #372.
> Update ribbon mode dendrogram selection when changing detail maps

- NGCHM/WebContent/chm.html
- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/MatrixManager.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/PaneControl.js
- NGCHM/WebContent/javascript/PluginInstanceManager.js
- NGCHM/WebContent/javascript/UI-Manager.js
- NGCHM/WebContent/javascript/UserHelpManager.js
This pull request implements changes to the button appearance and behavior I promised when discussing the 'dendrogram selection lost dialog' we discussed recently.
Specifically, it:
- changes the buttons on that dialog from Cancel and Close to Undo and OK, with OK being the default,
- makes the "Save to .NGCHM" button the default when saving a NGCHM,
- makes pressing the Enter key execute the default button if it exists, otherwise it just cancels the dialog
- renders the default button, if any, differently from the others.
> Feedback fixups

- NGCHM/WebContent/javascript/NgChm.js
NgChm.importNS called from chm.html results in an error in Safari, preventing the page from loading.
> Fix issue that prevents Safari loading restructured system

- .github/workflows/create-build-tag.yml
- NGCHM/WebContent/javascript/CompatibilityManager.js
This PR adds a GitHub Action Workflow that will add a new tag to the repo upon pushes to the 'main' branch. This tag will be based on the version number in CompatibilityManager.js and existing build tags in the repo. See example below.
**GitHub Actions included in this workflow** 
This workflow includes three GitHub Actions:
1. [actions/checkout](https://github.com/marketplace/actions/checkout)
This is for checking out the code in order to extract the version number from CompatibilityManager.js
2. [marohrdanz/extract-version-from-file](https://github.com/marohrdanz/extract-version-from-file)
This is a quick-and-dirty action created to extract the version number from CompatibilityManager.js. There **has** to be a better way to do this. We added the requirement for a version number prefix …
> Create Build Tag w/ GitHub Actions

- NGCHM/WebContent/javascript/CompatibilityManager.js
Force bumping version number, which I should have done *before* merging new-bug-fixes.
> Bump version number

- Dockerfile
- NGCHM/WebContent/javascript/API.js
- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/UI-Manager.js
Three small fixes to NG-CHM:
- one I had in my queue (explicitly specify viewer artifacts to include: without it extraneous files in my environment were being included),
- one was inspired by the view port element missing bug in the builder (for other embedded maps), and
- one required by fixes to the builder (not listening to key down events outside the NG-CHM), but which can also impact other cases of embedded NG-CHMs.
> Three fixes

- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
Nothing to draw if bar height <= zero.
Negative height bars try to allocate a matrix of negative length, hence the error.
> Don't attempt to draw zero height column covariate bars. Fixes issue #499.

- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/Linkout.js
These two commits address the memory issues with downloading large TSV files from the NG-CHM (see issue #502).
The first tries to minimize the memory required.
The second shows a warning dialog for large downloads.  It's currently set to show at 1 million array elements or more. This is way less than I've ever encountered issues.
The dialog also shows a progress bar during the large download and the user can cancel the download at any time.
> Address issues when downloading large matrices as tsv data.

- .github/workflows/build-NGCHMSupportFiles.yml
- .github/workflows/create-tag-and-build-NG-CHM-Artifacts.yml
This is a fix for the [failed action](https://github.com/MD-Anderson-Bioinformatics/NG-CHM/actions/runs/5293516110) during the release of 2.24.0.
Analysis showed the failure was due to the code trying to run on what appears to be a minified version of custom.js, and getting to the part for the cbioportal logo:
```js
logo: "https://www.cbioportal.org/images/cbioportal_logo.png",
```
This part includes the search string "images/", which is hard-coded into `CompilerUtilities.java`, therefore triggering an attempt to copy a file 'cbioportal_logo.png'. Of course that file does not exist in this repo, resulting in failure of the action.
For reasons **I do not understand**, changing the runner from macOS to ubuntu eliminates the problem (I tested in a personal fork of this repo).
In addition to …
> Actions fix for releases

- .github/workflows/build-NGCHMSupportFiles.yml
The recent manually triggered run of build-NGCHMSupportFiles.yml [failed](https://github.com/MD-Anderson-Bioinformatics/NG-CHM/actions/runs/5327325468).
Reason for the failure: the action obtains the software version from the release tag. But there was no release tag because the action was triggered manually, so there was no version number. Therefore the building of the NGCHM-R package failed with error: `Malformed package version.`
To resolve the issue, this pull request updates the action use our [previously written custom github action](https://github.com/marohrdanz/extract-version-from-file) to extract the version number from CompatibilityManager.js. This is the same mechanism used by create-tag-and-build-NG-CHM-Artifacts.yml for obtaining the software version number (see Pull Request …
> Get version from action instead of tag

- NGCHM/WebContent/javascript/MatrixManager.js
Bug fix.  "Home button" functionality was moved, but matrixManager was still looking for back_btn when collectionHome parameter was given.  back_btn was removed in commit 76964e6.
> Remove ref to "back_btn" that was removed from chm.html

- NGCHM/WebContent/javascript/DetailHeatMapEvent.js
- NGCHM/WebContent/javascript/Linkout.js
Safari sends a control-click event when other browsers don't.  The extra event causes the just opened matrix/label menu to close.
This fix: don't close a matrix/label menu if the control key is pressed.
This fixes a major (show-stopper) bug for Safari users, so I would like it released asap.
P.S. We also need to bump the version number.
> Prevent Matrix/Label menu closing immediately in Safari. See issue #529.

- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
Gap/cut color was not updating in the summary map.  See issue #501.
The cause was that the gap/cut color was not included in the saved drawing properties that determines when a redraw is needed.
This fix adds the gap/cut color to the saved properties.
> Fix changing gap/cut color not updating in Summary Map

- NGCHM/WebContent/chm.html
Chrome now complains about label elements with missing or incorrect "for" attributes. See issue #505.
I found four \<label> elements in chm.html that were semantically labels, but not labels in the strict HTML sense as referring to a specific form input element.
I changed them to plain \<span> elements.  Since we weren't formatted them any differently from plain elements, I didn't add a class field that we could use as a css selector in the future.  I could easily be convinced to add one.
> Fix chrome console errors about bad label elements

- .github/workflows/NG-CHM-Artifacts_push_main.yml
- .github/workflows/NG-CHM-Artifacts_release.yml
- .github/workflows/NGCHMSupportFiles_release.yml
This merge request addresses the following issues with GitHub Actions:
- NGCHMSupportFiles action failed because of newly added vignette
- Issue: #534
- Resolution: add knitr to GitHub Action workflow to allow vignette to build
- NG-CHM-Artifacts actions leave old minified js files in viewer.build/server.app/javascript
- Issue: #528
- Resolution: add a `git rm` to remove these old files
> Address GitHub Actions issues

- NGCHM/src/mda/ngchm/datagenerator/ShaidyRMapGen.java
This is bug fix for this issue in the NGCHM R package repo: https://github.com/MD-Anderson-Bioinformatics/NGCHM-R/issues/35
Strictly speaking, this change in ShaidyRMapGen.java is all that is required to address the bug. However, for other color variables, the R code checks that the color name is valid. That check is included in a related PR in the NGCHM R package repo: https://github.com/MD-Anderson-Bioinformatics/NGCHM-R/pull/65
> Convert cuts_color to hex if needed

- NGCHM/WebContent/javascript/Customization.js
- NGCHM/WebContent/javascript/custom/custom.js
This PR adds a linkout to canSAR.ai: https://cansar.ai
This linkout is for UniProt primary accession numbers and gene names. The data in canSAR.ai data is referenced via protein primary accession numbers, so for gene names this linkout queries UniProt to retrieve the primary accession number of the protein corresponding to the gene.
Because of the UniProt query for gene names, the linkout is asynchronous. The viewer code has been updated to allow for handling asynchronous linkouts.
> Add asynchronous canSAR.ai linkout

- NGCHM/WebContent/javascript/Customization.js
Allows site manager to specify multiple customization scripts using the data-ngchm-custom-file attribute on the document.body element. Customization scripts are separated by semicolons (;) and trimmed.
Example
`<body ... data-ngchm-custom-file="javascript/custom/custom.js; site.js">`
Outstanding issues:
Currently there is no way for each script to specify its own version number.  Only the last version number set is kept.
> Allow the site manager to specify multiple custom.js files

- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/ColorMapManager.js
- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/PaneControl.js
- NGCHM/WebContent/javascript/custom/custom.js
This pull request addresses two feature requests: 
1. Special coordinates
If the NG-CHM has covariate bars for coordinates (e.g. PCA, UMAP), Pane Menu entries to directly open those special coordinates in the plugin are shown. (Screenshot below)
2. "All Black" gear menu dropdown option
A dropdown option to color points all black is added to the "Color By" dropdown. If no other covariates available, this is the default.
Example: Below is a screenshot of the pane menu for an NG-CHM with special coordinate covariate bars. In this example, clicking on "PCA (column)" under 2D Scatter Plot will directly open the 2D scatter plot for the PCA coordinates, clicking "UMAP (column)" under 2D Scatter plot will directly open the 2D scatter plot for UMAP coordinates, etc. etc.
> Special coordinates and black points option

- NGCHM/WebContent/javascript/custom/custom.js
See enhancement request #551 for more details.
This commit disables link outs for COSMIC, Decipher, DepMap, and Ideogram Viewer if property "bio.species" is set to anything other than "Homo_sapiens". (List provided by Faiza.)
We still define the Plugin so that it shows up in the list of installed plugins, but do not define any link outs so that it does not appear in the list of active plugins.
Note that the same mechanism could be applied (in reverse) for link outs that only work for a non-human species.
> Disable link outs that do not work for non-human bio.species

- NGCHM/WebContent/javascript/CompatibilityManager.js
We have added a backwards-compatible feature: allowing for multi-panel initialization from the R package (#553)
> Bump version number: 2.25.0 -> 2.26.0

- NGCHM/WebContent/chm.html
- NGCHM/WebContent/css/NGCHM.css
- NGCHM/WebContent/javascript/ColorMapManager.js
- NGCHM/WebContent/javascript/ColorPalettes.js
- NGCHM/WebContent/javascript/CompatibilityManager.js
- NGCHM/WebContent/javascript/Customization.js
- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/DetailHeatMapEvent.js
- NGCHM/WebContent/javascript/DetailHeatMapManager.js
- NGCHM/WebContent/javascript/Linkout.js
- NGCHM/WebContent/javascript/MatrixManager.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/PdfGenerator.js
- NGCHM/WebContent/javascript/SummaryHeatMapDisplay.js
- NGCHM/WebContent/javascript/TCGACompendium/custom.js
- NGCHM/WebContent/javascript/UI-Manager.js
- NGCHM/WebContent/javascript/UI-Table.js
- NGCHM/WebContent/javascript/UserHelpManager.js
- NGCHM/WebContent/javascript/UserPreferenceManager.js
- NGCHM/WebContent/javascript/custom/custom.js
- Enable the user to select a continuous covariate for the "top items" on an axis.
- The entries with the largest values of that covariate will be the top items.
- Allows for simpler and more flexible ways of picking the top items and provides for expanded capabilities in the future.
- This originally removed the ability to specify the top items directly.
- Following discussion in the group meeting, that ability was added back.
- Too much code changed between the original removal and subsequent restoration to remove that from the commit history.
Many changes aimed at improving the readability and maintainability of the CompatibilityManager. and the UserPreference Manager.
- There is still more that could be done.
Added the ability for users to edit the types and visibility of label parts. …
> Added capabilities to the User Preference Manager

- NGCHM/WebContent/javascript/DetailHeatMapDisplay.js
- NGCHM/WebContent/javascript/HeatMapClass.js
- NGCHM/WebContent/javascript/MatrixManager.js
- NGCHM/WebContent/javascript/NGCHM_Embed.js
- NGCHM/WebContent/javascript/NGCHM_Util.js
- NGCHM/WebContent/javascript/PaneControl.js
- NGCHM/WebContent/javascript/UI-Manager.js
- NGCHM/WebContent/javascript/custom/custom.js
- NGCHM/build_ngchmApp.xml
- NGCHM/src/mda/ngchm/util/NGCHM_Widgetizer.java
This pull request enhances MatrixManager.js with the ability to load multiple maps.  It does NOT provide any UI elements for the casual user to access any of those maps except the first to load.  That capability will be expanded in subsequent pull requests.
This pull request also allows embedded NG-CHMs to load maps from web sources as well as zip files.  This will allow faster loading of large maps if you're not aiming to let the user save the page for off-line use.
Internally, the heat map sources have been changed to API_SOURCE (a shaidy server),  WEB_SOURCE (an unzipped NG-CHM in a web directory), or ZIP_SOURCE (a zip file, blob, etc.)
The HeatMap.source method has been replaced by the MMGR.getSource function.
> Allow loading of multiple ngchms
